spring:
  application:
    name: BtgChallenge
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/btg_challenge}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false
server:
  servlet:
    context-path: /api
game-api:
  url: https://api.sampleapis.com/playstation/games
jwt:
  # The secret key must be at least 256 bits (32 characters) long.
  secret: ${JWT_SECRET:Th1sIsAReallyL0ngAndSecur3S3cretKeyF0rJWT}
  expiration: ${JWT_EXPIRATION:86400}
